### ISSUE TITLE
Game crashes when entering world / server.

### ISSUE THREAD

**Issue by ghost** [UpcraftLP/Orderly#9] opened 2019-08-16 23:44 UTC
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!
 
Time: 8/15/19 10:17 PM
Description: Unexpected error
 
java.lang.NullPointerException: Unexpected error
    at io.github.prospector.orderly.HealthBarRenderer.render(HealthBarRenderer.java:46)
    at net.minecraft.class_761.handler$render$zzm000(class_761.java:2773)
    at net.minecraft.class_761.method_3271(class_761.java:1034)
    at net.minecraft.class_757.method_3178(class_757.java:1207)
    at net.minecraft.class_757.method_3188(class_757.java:1032)
    at net.minecraft.class_757.method_3192(class_757.java:792)
    at net.minecraft.class_310.method_1523(class_310.java:954)
    at net.minecraft.class_310.method_1514(class_310.java:410)
    at net.minecraft.client.main.Main.main(Main.java:155)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Head --
Thread: Client thread
Stacktrace:
    at io.github.prospector.orderly.HealthBarRenderer.render(HealthBarRenderer.java:46)
    at net.minecraft.class_761.handler$render$zzm000(class_761.java:2773)
    at net.minecraft.class_761.method_3271(class_761.java:1034)
    at net.minecraft.class_757.method_3178(class_757.java:1207)
    at net.minecraft.class_757.method_3188(class_757.java:1032)
 
-- Affected level --
Details:
    All players: 3 total; [class_746['iCats'/6588, l='MpServer', x=243.24, y=65.00, z=-550.75], class_745['Walkmen'/454, l='MpServer', x=270.30, y=62.88, z=-472.30], class_745['Punduck'/2616, l='MpServer', x=282.34, y=64.00, z=-473.93]]
    Chunk stats: Client Chunk Cache: 361, 190
    Level dimension: minecraft:overworld
    Level name: MpServer
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: {}
    Level spawn location: World: (199,63,112), Chunk: (at 7,3,0 in 12,7; contains blocks 192,0,112 to 207,255,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 648659 game time, 409258 day time
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Server brand: vanilla
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.class_638.method_8538(class_638.java:574)
    at net.minecraft.class_310.method_1587(class_310.java:1923)
    at net.minecraft.class_310.method_1514(class_310.java:430)
    at net.minecraft.client.main.Main.main(Main.java:155)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
 
-- System Details --
Details:
    Minecraft Version: 1.14.4
    Minecraft Version ID: 1.14.4
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1429773016 bytes (1363 MB) / 2046820352 bytes (1952 MB) up to 2147483648 bytes (2048 MB)
    CPUs: 4
    JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
    Fabric Mods:
        blue_endless_jankson: jankson 1.1.0
        cloth: Cloth Events 0.4.0
        cloth-config2: Cloth Config v2 0.5.3
        fabric: Fabric API 0.3.1+build.208
        fabric-api-base: fabric-api-base 0.1.0+b494ebeb42
        fabric-biomes-v1: fabric-biomes-v1 0.1.0+896c7fbb42
        fabric-commands-v0: fabric-commands-v0 0.1.1+b494ebeb42
        fabric-containers-v0: fabric-containers-v0 0.1.2+b494ebeb42
        fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+b494ebeb42
        fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.1+9f55aa7042
        fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.1+9f55aa7042
        fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.1+eff46b3d42
        fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+1e69a0a542
        fabric-keybindings-v0: fabric-keybindings-v0 0.1.1+7dfef87c42
        fabric-loot-tables-v1: fabric-loot-tables-v1 0.1.0+b494ebeb42
        fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+ab421b9c42
        fabric-models-v0: fabric-models-v0 0.1.0+5914746342
        fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+b494ebeb42
        fabric-networking-v0: fabric-networking-v0 0.1.3+9f55aa7042
        fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+9b03381f42
        fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.2+9b03381f42
        fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.1+9b03381f42
        fabric-renderer-indigo: fabric-renderer-indigo 0.1.10+f0fe03ff42
        fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+b494ebeb42
        fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.1+39442fc242
        fabric-rendering-v0: fabric-rendering-v0 0.1.1+6dad974e42
        fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.2+232e294c42
        fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.1+b494ebeb42
        fabric-textures-v0: fabric-textures-v0 0.1.4+b494ebeb42
        fabricloader: Fabric Loader 0.4.8+build.159
        lightoverlay: Light Overlay 3.4
        mm: Manningham Mills 1.6
        modmenu: Mod Menu 1.7.6+build.115
        net_fabricmc_stitch: stitch 0.2.1.61
        optifabric: Optifabric 0.5.1
        orderly: Orderly 1.1.0+build.13
        org_slf4j_slf4j-api: slf4j-api 1.7.26
        org_slf4j_slf4j-simple: slf4j-simple 1.7.26
        org_zeroturnaround_zt-zip: zt-zip 1.13
        roughlyenoughitems: Roughly Enough Items 2.9.8+build.149
        voxelmap: VoxelMap 1.9.13
    Launched Version: fabric-loader-0.4.8+build.159-1.14.4
    LWJGL: 3.2.2 build 10
    OpenGL: Radeon(TM) RX 460 Graphics GL version 4.5.13492 Compatibility Profile Context 22.19.677.257, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.
 
    Using VBOs: Yes
    Is Modded: Definitely; Client brand changed to 'fabric'
    Type: Client (map_client.txt)
    Resource Packs: vanilla, file/§6§k!!§1§lCats §5§nNew Pak§6§k!!§b v1.14
    Current Language: English (United Kingdom)
    CPU: 4x Intel(R) Core(TM) i5 CPU 650 @ 3.20GHz

**Comment by VaanNG** [comment] 2019-08-18 10:43
[crash-2019-08-18_11.29.09-client.txt](https://github.com/UpcraftLP/Orderly/files/3512904/crash-2019-08-18_11.29.09-client.txt)

**Comment by MerryPlace** [comment] 2019-08-21 05:34
I have the same problem

**Comment by UpcraftLP** [comment] 2019-08-22 09:35
duplicate of #7

**Closed as completed by UpcraftLP** 2019-08-22 09:35 UTC
Labels: duplicate
