### ISSUE TITLE
NPE caused by vanilla MP server

### ISSUE THREAD

**Issue by hugeblank** [UpcraftLP/Orderly#7] opened 2019-08-16 05:08 UTC
It may not be caused by it being in a vanilla MP server, this crash report in particular was though.
This was also done on a machine that is not my own. I have no problems running 1.1.0.

```---- Minecraft Crash Report ----
// There are four lights!

Time: 8/15/19 9:12 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at io.github.prospector.orderly.HealthBarRenderer.render(HealthBarRenderer.java:46)
	at net.minecraft.class_761.handler$render$zzm000(class_761.java:2773)
	at net.minecraft.class_761.method_3271(class_761.java:706)
	at net.minecraft.class_757.method_3178(class_757.java:859)
	at net.minecraft.class_757.method_3188(class_757.java:766)
	at net.minecraft.class_757.method_3192(class_757.java:630)
	at net.minecraft.class_310.method_1523(class_310.java:954)
	at net.minecraft.class_310.method_1514(class_310.java:410)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at io.github.prospector.orderly.HealthBarRenderer.render(HealthBarRenderer.java:46)
	at net.minecraft.class_761.handler$render$zzm000(class_761.java:2773)
	at net.minecraft.class_761.method_3271(class_761.java:706)
	at net.minecraft.class_757.method_3178(class_757.java:859)
	at net.minecraft.class_757.method_3188(class_757.java:766)

-- Affected level --
Details:
	All players: 5 total; [class_746['soapteasammi'/1606, l='MpServer', x=146.86, y=71.00, z=-424.30], class_745['cosmoddity'/693, l='MpServer', x=171.69, y=72.00, z=-479.72], class_745['F7_Sandman'/405, l='MpServer', x=182.33, y=73.94, z=-515.70], class_745['Megan21098'/536, l='MpServer', x=181.30, y=72.88, z=-493.51], class_745['Nessoscar'/906, l='MpServer', x=168.17, y=72.00, z=-508.91]]
	Chunk stats: Client Chunk Cache: 361, 122
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-96,63,-165), Chunk: (at 0,3,11 in -6,-11; contains blocks -96,0,-176 to -81,255,-161), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 16713780 game time, 4638019 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:421)
	at net.minecraft.class_310.method_1587(class_310.java:1923)
	at net.minecraft.class_310.method_1514(class_310.java:430)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2005568040 bytes (1912 MB) / 2818572288 bytes (2688 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin 1.0.7
		cloth-config2: Cloth Config v2 0.5.3
		fabric: Fabric API 0.3.1+build.208
		fabric-api-base: fabric-api-base 0.1.0+59147463
		fabric-biomes-v1: fabric-biomes-v1 0.1.0+896c7fbb42
		fabric-commands-v0: fabric-commands-v0 0.1.1+b494ebeb42
		fabric-containers-v0: fabric-containers-v0 0.1.2+b494ebeb42
		fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+b494ebeb42
		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.1+9f55aa7042
		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.1+9f55aa7042
		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.1+eff46b3d42
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+1e69a0a542
		fabric-keybindings-v0: fabric-keybindings-v0 0.1.1+7dfef87c42
		fabric-loot-tables-v1: fabric-loot-tables-v1 0.1.0+b494ebeb42
		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+ab421b9c42
		fabric-models-v0: fabric-models-v0 0.1.0+5914746342
		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+b494ebeb42
		fabric-networking-v0: fabric-networking-v0 0.1.3+9f55aa7042
		fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+9b03381f42
		fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.2+9b03381f42
		fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.1+9b03381f42
		fabric-renderer-indigo: fabric-renderer-indigo 0.1.10+f0fe03ff42
		fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+b494ebeb42
		fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.1+39442fc242
		fabric-rendering-v0: fabric-rendering-v0 0.1.1+6dad974e42
		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.2+232e294c42
		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.1+b494ebeb42
		fabric-textures-v0: fabric-textures-v0 0.1.4+b494ebeb42
		fabricloader: Fabric Loader 0.4.8+build.159
		itemscroller: Item Scroller 0.15.0-dev.20190720.190250
		malilib: MaLiLib 0.10.0-dev.20
		modmenu: Mod Menu 1.7.6+build.115
		orderly: Orderly 1.1.0+build.13
		voxelmap: VoxelMap 1.9.13
	Launched Version: fabric-loader-0.4.8+build.159-1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: AMD Radeon R5 Graphics GL version 4.5.14009 Compatibility Profile Context 21.19.144.1281, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/VanillaTweaks_r216950.zip
	Current Language: English (US)
	CPU: 4x AMD A10-9600P RADEON R5, 10 COMPUTE CORES 4C+6G****
```

**Comment by UpcraftLP** [comment] 2019-08-22 10:20
most likely caused by #11, so should be fixed with that commit. I'll publish a new version later.

**Closed as completed** 2019-08-22 10:23 UTC
Labels: duplicate
