### ISSUE TITLE
Name Tag Issue

### ISSUE THREAD

**Issue by xDeathy** [UpcraftLP/Orderly#10] opened 2019-08-18 19:06 UTC
Whenever I Put An Name Tag on an entity it shows a long Name which is in fact the codes such like : **textComponet{text=**.....etc 
I Hope It Gets Fixed Soon !
Here is a pic to show you what i mean !
[https://imgur.com/Cd0otzJ](url)

**Comment by luke-bravenboer** [comment] 2019-08-20 03:19
You need to update, this is fixed in the latest version (1.1.0).

Duplicate of #4

**Closed as completed** 2019-08-22 07:21 UTC
Labels: duplicate
